/*
* sones GraphDB - Open Source Edition - http://www.sones.com
* Copyright (C) 2007-2010 sones GmbH
*
* This file is part of sones GraphDB Open Source Edition (OSE).
*
* sones GraphDB OSE is free software: you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as published by
* the Free Software Foundation, version 3 of the License.
* 
* sones GraphDB OSE is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU Affero General Public License for more details.
*
* You should have received a copy of the GNU Affero General Public License
* along with sones GraphDB OSE. If not, see <http://www.gnu.org/licenses/>.
* 
*/

/* 
 * MediaRSS_IO_Extensions
 * Achim 'ahzf' Friedland, 2010
 */

#region Usings

using System;
using System.Text;

using sones.GraphFS.DataStructures;

using sones.GraphDB.Structures;


using sones.Lib;
using sones.GraphDB.Result;
using sones.GraphDB.NewAPI;

#endregion

namespace sones.GraphIO.MediaRSS
{

    /// <summary>
    /// Extension methods to transform a QueryResult and a DBObjectReadout into an
    /// application/json representation an vice versa.
    /// </summary>

    public static class MediaRSS_IO_Extensions
    {


        #region ToMediaRSS(this myQueryResult)

        public static String ToMediaRSS(this QueryResult myQueryResult,
                                        String myGalleryTitle       = "GreenIris",
                                        String myGalleryDescription = "Generated by a sones GraphDS graph traversal",
                                        String myGalleryCopyright   = null,
                                        String myGalleryLanguage    = "en-en")
        {

            var myStringBuilder = new StringBuilder();

            myStringBuilder.AppendLine("<channel>").AppendLine();

            #region Successful, or...

            if (myQueryResult.ResultType == ResultType.Successful)
            {

                if (myGalleryTitle != "")
                    myStringBuilder.Append("<title>").Append(myGalleryTitle).AppendLine("</title>");

                if (myGalleryDescription != "")
                    myStringBuilder.Append("<description>").Append(myGalleryDescription).AppendLine("</description>");

                if (!myGalleryCopyright.IsNullOrEmpty())
                    myStringBuilder.Append("<copyright>").Append(myGalleryCopyright).AppendLine("</copyright>");

                if (myGalleryLanguage != "")
                    myStringBuilder.Append("<language>").Append(myGalleryLanguage).AppendLine("</language>");

                myStringBuilder.AppendLine();

                //<!-- <logo url="pl_images/logo.gif" /> -->
                //<!-- <atom:icon>http://www.mywebsite.com/images/logo.gif</atom:icon> -->
                //<!-- <link>http://www.ahzf.de/cooliris.html</link> -->


                if (myQueryResult != null && myQueryResult.Vertices != null)
                    if (myQueryResult.Vertices != null && myQueryResult.Vertices != null)
                        foreach (var _Vertex in myQueryResult)
                            if (_Vertex != null)
                                myStringBuilder.Append(_Vertex.ToMediaRSS());

            }

            #endregion

            #region ...error(s) occurred!

            else
            {

                myStringBuilder.Append("<title>Error(s) occurred!</title>");

                myStringBuilder.AppendLine("<description>");

                if (myQueryResult != null && myQueryResult.Errors != null)
                    foreach (var _Error in myQueryResult.Errors)
                    {
                        myStringBuilder.AppendLine("ErrorCode: " + _Error.GetType().ToString());
                        myStringBuilder.AppendLine("ErrorDescription: " + _Error.ToString());
                    }

                myStringBuilder.AppendLine("</description>");

                myStringBuilder.Append("<language>en-en</language>");

            }

            #endregion

            myStringBuilder.AppendLine().AppendLine("</channel>");

            return myStringBuilder.ToString();

        }

        #endregion

        #region ToMediaRSS(this myVertex)

        public static String ToMediaRSS(this Vertex myVertex)
        {

            var myStringBuilder = new StringBuilder();

            var _UUID           = myVertex.UUID;
            var _filename       = myVertex.GetStringProperty("Filename");
            var _MIMEType       = myVertex.GetStringProperty("MIMEType");
            var _title          = myVertex.GetStringProperty("Title");
            var _description    = myVertex.GetStringProperty("Description");

            if (_UUID != null && _filename != null && _MIMEType != null && _title != null && _description != null)
            {

                myStringBuilder.AppendLine("<item>");
                myStringBuilder.Append("<title>").Append(_title).AppendLine("</title>");
                myStringBuilder.Append("<link>/photos/bin/").Append(_UUID).Append("/").Append(FSConstants.DefaultEdition).AppendLine("</link>");
                myStringBuilder.Append("<media:thumbnail url=\"/photos/bin/").Append(_UUID).Append("/").Append("thumbnail").AppendLine("\" />");
                myStringBuilder.Append("<media:content   url=\"/photos/bin/").Append(_UUID).Append("/").Append(FSConstants.DefaultEdition).AppendLine("\" type=\"image/jpeg\" />");
                //myStringBuilder.Append("<media:content   url=\"/photos/bin/").Append(_uuid).Append("/").Append(FSConstants.DefaultEdition).AppendLine("\" type=\"text/html\" />");
                myStringBuilder.Append("<media:description>").Append(_description).AppendLine("</media:description>");
                myStringBuilder.AppendLine("</item>").AppendLine();

            }

            return myStringBuilder.ToString();

        }

        #endregion

        #region MediaRSSBuilder(myFunc)

        public static String MediaRSSBuilder(Action<StringBuilder> myFunc)
        {

            var _StringBuilder = new StringBuilder();


            _StringBuilder.AppendLine("<?xml version=\"1.0\" encoding=\"utf-8\" standalone=\"yes\"?>");
            _StringBuilder.AppendLine("<rss version=\"2.0\" xmlns:media=\"http://search.yahoo.com/mrss/\" xmlns:atom=\"http://www.w3.org/2005/Atom\">");

            myFunc(_StringBuilder);

            _StringBuilder.AppendLine("</rss>").AppendLine();

            return _StringBuilder.ToString();

        }

        #endregion

    }

}
